defaults:
  - train_loader: small
  - validation_loader: small
  - model: base
  - _self_

writer:
  experiment_name: "Juls-train"

hydra:
  mode: MULTIRUN
  sweep:
    dir: multirun/${writer.experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  output_subdir: null
  sweeper:
    params:
      model.num_epochs: 5
      train_loader.num_augmentations: 5
      train_loader.batch_size: 20
      model.apply_weight_loss: False
      model.learning_rate: 0.0005


