defaults:
  - terramind
  - _self_

experiment_name: dev-sweeps-large

hydra:
  mode: MULTIRUN
  sweep:
    dir: /users/PGS0218/julina/projects/geography/damage_mapping_terramind/V2/data/experiments/${experiment_name}/${hydra.job.config_name}_${now:%Y-%m-%d}_${now:%H%M%S}
    subdir: ${hydra.job.num}
  sweeper:
    params:
      trainer.n_epochs: 8, 20
      # model.learning_rate: 0.0005
      # model.apply_weight_loss: true,false
      # model.weight_type: inverse,pixels
      # model.num_classes: 3
      # train_loader.num_augmentations: 5
      # train_loader.batch_size: 4
      criterion.name: dice_focal, dice, ce
      # criterion.apply_weight_loss: true
      # criterion.weight_type: inverse
      # criterion.dice_weight: 0.5
      # criterion.focal_weight: 0.5
      # criterion.focal_gamma: 2.0
      # criterion.focal_alpha: null
      # criterion.dice_smooth: 1e-6
