defaults:
  - terramind_small
  - _self_

experiment_name: dev-sweeps-small

hydra:
  mode: MULTIRUN
  sweep:
    dir: /users/PGS0218/julina/projects/geography/damage_mapping_terramind/V2/data/experiments/${experiment_name}/${hydra.job.config_name}_${now:%Y-%m-%d}_${now:%H%M%S}
    subdir: ${hydra.job.num}
  sweeper:
    params:
      trainer.n_epochs: 5,8,12
      model.learning_rate: 0.0005,0.0001
      model.apply_weight_loss: true,false
      model.weight_type: inverse,pixels
