defaults:
  - base
  - _self_

experiment_name: dev-run-large

train_loader: 
  modalities:
    S2L2A:
      before: Images_large/Train/Before/S2L2A
      after: Images_large/Train/After/S2L2A
    S1GRD:
      before: Images_large/Train/Before/S1GRD/DESC
      after: Images_large/Train/After/S1GRD/DESC
  label_dir: Images_large/Train/Labels
  num_augmentations: 5
  patch_size: 224
  stride: 224
  preload: False
  batch_size: 4
  shuffle: True
  num_workers: 2

validation_loader: 
  modalities:
    S2L2A:
      before: Images_large/Train/Before/S2L2A
      after: Images_large/Train/After/S2L2A
    S1GRD:
      before: Images_large/Train/Before/S1GRD/DESC
      after: Images_large/Train/After/S1GRD/DESC
  label_dir: Images_large/Train/Labels
  patch_size: 224
  stride: 224
  preload: False
  batch_size: 4
  shuffle: False
  num_workers: 2

holdout_loader:
  modalities:
    S2L2A:
      before: Images_large/Test/Before/S2L2A
      after: Images_large/Test/After/S2L2A
  label_dir: Images_large/Test/Labels
  patch_size: 224
  stride: 224
  num_workers: 2

model: 
  num_classes: 3
  apply_weight_loss: False
  weight_type: inverse
  ignore_index : 0
  positive_class: 2
  negative_class: 1
  TM_version: "terramind_v1_base"
  pretrained: True
  modalities: ["S2L2A", "S1GRD"]
  TM_finetune: False
  learning_rate: 0.0005
  num_epochs: 8
  seed: 22

trainer:
  n_epochs: 20
  log_interval: 1
  
use_wandb: false
